services:
  accounts:
      image: naveenkumarmishra/accounts:latest
      ports:
        - "8080:8080"
      networks:
        - bank-network
  cards:
      image: naveenkumarmishra/cards:latest
      ports: 
        - "8082:8082"
      networks: 
        - bank-network
        
  Loan:
      image: naveenkumarmishra/loans:latest
      ports: 
        - "9500:9500"
      networks: 
        - bank-network
networks:
  bank-network: {}